name: build & deploy Angular to GitHub Pages

on:
  push:
    branches: [ main ]   # change if you use master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'   # or 18/16 depending on your project

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build --if-present --silent
        # ensure package.json "build" runs: ng build --configuration production

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/holyredeemer   # <-- set this to your actual dist folder
